name: hands2gether
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  google_sign_in: ^5.4.2
  provider: ^6.0.3
  cloud_firestore: ^3.5.1
  font_awesome_flutter: ^10.2.1
  ribbon_widget: ^1.0.5
  carousel_slider: ^4.1.1
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  cached_network_image: ^3.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/