name: hands2gether
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.4
  google_sign_in: ^5.4.2
  provider: ^6.0.3
  cloud_firestore: ^4.3.1
  font_awesome_flutter: ^10.2.1
  ribbon_widget: ^1.0.5
  carousel_slider: ^4.1.1
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  cached_network_image: ^3.2.1
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.11.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  country_list_pick: ^1.0.1+6
  simple_moment: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/launcher/logo.png"
    background_color: "#f5f5f5"
    theme_color: "#f5f5f5"
  windows:
    generate: true
    image_path: "assets/launcher/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/launcher/logo.png"